### ISSUE TITLE
Dual hole footprint question

### ISSUE THREAD

**Issue by mattdibi** [keebio/Keebio-Parts.pretty#1]
Hi,
I've got a questions about your footprint library.

I'm working on a split keyboard PCB and would like to use your Cherry MX dual hole footprint. In your library there are some duplicates (Hybrid_PCB_100H_Dual_hole, Hybrid_PCB_100H_Dual_hole-flip, ProMicro footprints etc.) which one should I use? Are there any significant difference between them?

BTW thank you for sharing this library! 😄

**Comment by nooges** [comment]
You can ignore the `-flip` ones, I sometimes use those if I'm putting the diode on the other side of the switch.

**Comment by mattdibi** [comment]
Thanks for your reply.
