### ISSUE TITLE
Pro Micro 3d shape is missing.

### ISSUE THREAD

**Issue by HarrierPigeon** [keebio/Keebio-Parts.pretty#5]
3D shape name refers to location ``/Users/danny/Documents/proj/custom-keyboard/kicad-libs/3d_modules/…``` instead of a location inside of a keebio library.

**Comment by nooges** [comment]
This is a bit tricky to handle, as relative folder references are done with respect to the PCB project folder, as opposed to the folder of the library, so not really an easy fix here.
