### ISSUE TITLE
Errors loading some of the more recent footprints in KiCad

### ISSUE THREAD

**Issue by gabeklavans** [keebio/Keebio-Parts.pretty#8]
I'm encountering these error messages when trying to load the footprint library. I was specifically looking for the SK6812-MINI-E footprint, but it's not showing up in the library after closing out this error message.

**Errors were encountered loading footprints:**
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/Kailh-PG1350-1u-NoLED.kicad_mod"
line 24, offset 93
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/Kailh-PG1350-2.5u.kicad_mod"
line 68, offset 99
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/Kailh-PG1350-2u-NoLED.kicad_mod"
line 56, offset 99
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/Kailh-PG1350-2u-Vert-NoLED.kicad_mod"
line 56, offset 99
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/Kailh-PG1350-2u.kicad_mod"
line 68, offset 99
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/SK6812-MINI-E.kicad_mod"
line 17, offset 89
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/SW_SPST_TL3342.kicad_mod"
line 59, offset 84
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/TRRS-PJ-605.kicad_mod"
line 39, offset 98
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/TRRS-PJ-606.kicad_mod"
line 38, offset 101
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/USB-C-12-Pin-MidMount.kicad_mod"
line 13, offset 98
Expecting "at, drill, layers, net, die_length, solder_mask_margin, roundrect_rratio,
solder_paste_margin, solder_paste_margin_ratio, clearance,
zone_connect, fp_poly, primitives, thermal_width, or thermal_gap" in input/source
"C:\Users\gabek\Downloads\Keebio-Parts.pretty/WS2812B.kicad_mod"
line 15, offset 104

**Comment by ellisgl** [comment]
Also if you use the any of the  breakaway foot prints and then try to add another foot print (just clicking to add a foot print) KiCAD will crash.

**Comment by maciejmatczak** [comment]
Same errors for me, KiCAD 5.1.6.

**Comment by nooges** [comment]
Ah, I'm on the KiCAD nightlies, which probably changed some of the .kicad_mod format up.
